
services:
  dex:
    image: ghcr.io/dexidp/dex:v2.35.3
    volumes:
      - ./dex/dex-config.yaml:/etc/dex/dex-config.yaml
    command: ["dex", "serve", "/etc/dex/dex-config.yaml"]
    ports:
      - "5556:5556"
    networks:
      - my_network

  server:
    build: ./my-app
    env_file: ./my-app/.env
    ports:
      - "3001:3001"
    depends_on:
      - dex
    networks:
      - my_network
      
networks:
  my_network:
    driver: bridge
