services:
  db:
    image: postgres_db
    restart: always
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: password
       POSTGRES_DB: RestaurantDB
    ports:
      - "5432:5432"

  backend:
    image: backend_image
    depends_on:
      - db
    ports:
      - "3000:3000"

