issuer: http://localhost:5556/dex
storage:
  type: memory

web:
  http: 0.0.0.0:5556

skipApprovalScreen: true

connectors:
- type: mockCallback
  id: mock
  name: Example

staticClients:
  - id: my-app
    redirectURIs:
      - http://localhost:3001/callback
    secret: my-app-secret
    name: "My App"
    
    trustedPeers:
      - my-app


